import type { Metadata } from "next";
import "../../globals.css";
import AuthLayout from "@/src/shared/layouts/AuthLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body>
        <AuthLayout>{children}</AuthLayout>
      </body>
    </html>
  );
}
